print("in?\n")
count = len(open("../trace/rawfile952G_simple_LUN0.txt", "rU").readlines())
print("LUN0 = {}\n".format(count))
count = len(open("../trace/rawfile952G_simple_LUN1.txt", "rU").readlines())
print("LUN1 = {}\n".format(count))
count = len(open("../trace/rawfile952G_simple_LUN2.txt", "rU").readlines())
print("LUN2 = {}\n".format(count))
count = len(open("../trace/rawfile952G_simple_LUN3.txt", "rU").readlines())
print("LUN3 = {}\n".format(count))
count = len(open("../trace/rawfile952G_simple_LUN4.txt", "rU").readlines())
print("LUN4 = {}\n".format(count))
count = len(open("../trace/rawfile952G_simple_LUN6.txt", "rU").readlines())
print("LUN6 = {}\n".format(count))